### ISSUE TITLE
Better XCloud 5.5.1 crash when i started it

### ISSUE THREAD

**Issue by justfrank26** [redphx/better-xcloud-tv#2]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

LG TV 

### Operating System

webOS 8.3.0-28

### Android app/Browser Version

Chrome 94.0

### Better xCloud Version

5.5.1

### Reproduction Steps

When i open the app it refreshed two times and at the third it crashes immediately

**Comment by redphx** [comment]
Did you tried downgrading to 5.5.0?

**Comment by Chronos69** [comment]
I can confirm.
LG Oled C2
Webos 8.3.0-28

I start Xcloud, it seems stuck. After a few seconds (4-5) it restart. Same thing again, stuck for 4-5 seconds.
Then it crash and return to TV menu.

**Comment by Chronos69** [comment]
How can I install a previous version?

**Comment by justfrank26** [comment]
you have to use webos manager with clicking the install button and download in this site https://github.com/redphx/better-xcloud-webos/releases the version that you prefer

**Comment by justfrank26** [comment]
> Have you tried downgrading to 5.5.0?
and now i need to ask a question. Which is the version who had for the first time the feature "change game language".

**Comment by redphx** [comment]
did you test again with 5.5.3?

**Comment by Chronos69** [comment]
> did you test again with 5.5.3?

Hi. I just tested and keeps doing the exact same thing.
2 crashes (Maybe 3, I'm not sure) restarting the APP, and then the final crash closing the APP and places me on the LG menu.
Tested with 5.5.6

**Comment by jamasvk** [comment]
Same for me, LG G2

**Comment by redphx** [comment]
Check #7
