### ISSUE TITLE
[Bug] Crash 5.5.3 webOS 

### ISSUE THREAD

**Issue by RayneRPT** [redphx/better-xcloud-tv#4]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

OLED77B36LA

### Operating System

webOS 8.3.1-3607

### Android app/Browser Version

Not Applied

### Better xCloud Version

5.5.3

### Reproduction Steps

Hi, crash after a few seconds of opening the app ( page is refreshing continuously and crash at the 3rd refresh), it was working on version 5.5.0. Can't upload video since limit is 10mb.
Tried reinstalling the app and problem presists. 
Cheers.

**Comment by RayneRPT** [comment]
Bad click, for now I'm on 5.4.2 that is the most usable and stable one that have the streaming options available but unfortunately not all the app settings.

5.5.4 have the same issue. 

Hope you can find a fix.
Cheers

**Comment by ElSturge** [comment]
Using 5.5.6 and having the same problem on my LG TV. Will try downgrading the version when I get chance to see if that helps.

**Comment by Chronos69** [comment]
Can confirm. 2-3 crashes on 5.5.6 and kicks me out to the LG menu

**Comment by jamasvk** [comment]
Yep, exactly the same issue, LG G2

**Comment by RayneRPT** [comment]
> Can confirm. 2-3 crashes on 5.5.6 and kicks me out to the LG menu

5.5.0 is working but it doesn't have the app settings like server region etc but streaming options are there anyway OpenGL gives me black screen and throws an cloud error at screen after some seconds of playing sound and no image.. Don't know what's been going on with Better xcloud.

**Comment by redphx** [comment]
#2
