### ISSUE TITLE
[Bug] Can't login

### ISSUE THREAD

**Issue by rafelis1997** [redphx/better-xcloud-tv#5]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

55NANO77SRA

### Operating System

webOS 8.3.1

### Browser User-Agent

Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/94.0.4606.128 Safari/537.36 SmartTV/10.0 Colt/2.0

### Better xCloud Version

5.5.4

### Reproduction Steps

1. Open app
2. Tries to sign-in
3. Enters the login
4. 1 second later comes back to main page

**Comment by redphx** [comment]
Check #7

**Comment by lehas96** [comment]
got same issue..🥲
