### ISSUE TITLE
[Bug] 5.5.6 app crashing on LG G2

### ISSUE THREAD

**Issue by jamasvk** [redphx/better-xcloud-tv#6]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

LG OLED65G23LA

### Operating System

webos23 (8.3.0-28), SW ver. 13.30.80

### Browser User-Agent

![IMG_20240826_012806](https://github.com/user-attachments/assets/5db1635f-f36e-4d27-a1b0-a164de8cdeda)

### Better xCloud Version

5.5.6

### Reproduction Steps

Hi, crash after a few seconds of opening the app, page is refreshing continuously and crash at the 3rd refresh to TV menu, cannot move in the app menu, xbox controller connected or not does not change anything.
Tried reinstalling the app, the problem presists.
Thx.

**Comment by redphx** [comment]
#2

**Comment by jamasvk** [comment]
You advised to create new issue and then closed as not planned...wtf???

Dňa po 26. 8. 2024, 2:10 redphx ***@***.***> napísal(a):
