### ISSUE TITLE
[Bug] The script does not load the patches

### ISSUE THREAD

**Issue by GuilhermeAugustini** [redphx/better-xcloud-tv#7]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

55NANO77SRA

### Operating System

webOS 8.3.1

### Browser User-Agent

Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/94.0.4606.128 Safari/537.36 SmartTV/10.0 Colt/2.0

### Better xCloud Version

5.5.6

### Reproduction Steps

1. Open the app

### Screenshot/video

Although the script is loaded without errors, patches are not being loaded.
Debugging the script, I realized that in the Patcher class has the 'patchfunctionbind' function that intercepts in the client script the function call to load the chunks(.js).
My theory is the system takes time to load or load only after the site is loaded, which does not allow enabling some experimental XCLOUD functions.

In LG TV, patches are not being loaded.

![lg_logs_open](https://github.com/user-attachments/assets/798bd5ee-aaa4-41e7-92bf-f1fa47158133)

In website, patches are being loaded

![web-logs](https://github.com/user-attachments/assets/7239c0c4-b2de-48c7-99dd-3bc5cec1f911)

**Comment by redphx** [comment]
Please test again with version [5.1.3](https://github.com/redphx/better-xcloud-webos/releases/tag/v5.1.3)

**Comment by GuilhermeAugustini** [comment]
I tested and there was no change
![image](https://github.com/user-attachments/assets/debae645-83ee-4214-92db-67fde78e1785)

**Comment by GuilhermeAugustini** [comment]
How webOs load [userScript](https://github.com/webosose/wam/blob/7281fe01f1fd5803adafc28f7a9986862c210e50/src/platform/webengine/web_page_blink.cc#L889)

![image](https://github.com/user-attachments/assets/ccf272b1-a4fb-425c-83b4-de30efbe7dde)

**Comment by redphx** [comment]
Thanks. I need time to check this. Since I don't have a compatible TV it's not easy to work.

**Comment by redphx** [comment]
Try this version: [com.redphx.better-xcloud_5.7.8_all.ipk.zip](https://github.com/user-attachments/files/17217819/com.redphx.better-xcloud_5.7.8_all.ipk.zip)  

It's a lite version which only comes with some features

**Comment by GuilhermeAugustini** [comment]
I can't test it anymore, I don't have an LG TV anymore

**Comment by flipside101** [comment]
> Try this version: [com.redphx.better-xcloud_5.7.8_all.ipk.zip](https://github.com/user-attachments/files/17217819/com.redphx.better-xcloud_5.7.8_all.ipk.zip)
> 
> It's a lite version which only comes with some features

if i get some time ill give it a go

**Comment by rylenlobo** [comment]
i cant login i installed this same issue with 5.5.6
https://www.xbox.com/play/login/deviceCode  just redirect's back to xcloud homepage

**Comment by rylenlobo** [comment]
i have an LG TV i can test anytime

**Comment by redphx** [comment]
Test this version: [com.redphx.better-xcloud_5.8.5_all.ipk.zip](https://github.com/user-attachments/files/17404793/com.redphx.better-xcloud_5.8.5_all.ipk.zip)

It fixes the login problem, but only works if you're in xCloud supported regions, for now.

**Comment by jamasvk** [comment]
This 5.8.5 is working on LG G2 tv, nicely done! Thanks

**Comment by Fernan20881208** [comment]
Bro Coop Is not in this versión :(

**Comment by Fernan20881208** [comment]
Please add the Coop mode

**Comment by redphx** [comment]
> Bro Coop Is not in this versión :(

It was removed because it didn't work. Don't ask for it.

**Comment by rylenlobo** [comment]
Works great! now i can login also when setting the suggested settings it just shows a blank screen after the xbox logo shows up
thanks for fixing the login issue really appreciate it

**Comment by redphx** [comment]
I don't have a supported TV to test so it's impossible for me to debug. Please follow [this guide](https://webostv.developer.lge.com/develop/getting-started/app-debugging) and check the error logs in Console.  

Also when reporting bug, please share video/screenshot and TV model.

**Comment by flipside101** [comment]
righto , i have some time to look at things. ive installed com.redphx.better-xcloud_5.8.5_all.ipk and run up teh console. when i login it shows
![Screenshot 2024-11-16 114646](https://github.com/user-attachments/assets/c7fffa93-adf2-454f-bce2-80daca673b87)

**Comment by vuelacol2** [comment]
i also install the new version 5.8.5 but the same... it´s frozen like previusly bug 
LG OLED C1

**Comment by Carlos114820** [comment]
> Funciona muito bem! Agora eu posso fazer o login também ao aplicar as configurações sugeridas, ele apenas mostra uma tela em branco depois que o logotipo do Xbox aparece, obrigado por corrigir o problema de login, realmente agradeço
Hello, how did you solve it??

**Comment by redphx** [comment]
Move to #10
