### ISSUE TITLE
[Bug] Didn't play 

### ISSUE THREAD

**Issue by vuelacol2** [redphx/better-xcloud-tv#9]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

LG OLED C1

### Operating System

3.41.00

### Browser User-Agent

Chromium 87.0.3945.79

### Better xCloud Version

5.5.6

### Game list

All 

### Reproduction Steps

- Device name
TV LG OLED C1
- OS version
3.41.00
- Browser or app, name + version
Chromium 87.0.3945.79
- Country/Region
Colombia
- Script version
5.5.6
- What did you do? Steps to reproduce?
All the instructions of https://better-xcloud.github.io/lg-webos/
- Screenshot/video

Description:
I followed all the installation steps as outlined in the instructions. I installed the latest version of Better XCloud (5.5.6) and managed to open the game. However, the app does not recognize my Xbox controller, which I had previously connected via Bluetooth, and it does not progress beyond the loading screen (screenshot attached). I have reinstalled the app multiple times, but the issue persists.

No one else seems to have reported this problem, so I'm wondering if it might be related to my location (Colombia).

Steps to Reproduce:

Install Better XCloud (version 5.5.6).
Connect an Xbox controller via Bluetooth.
Open the game.
Expected Behavior:
The game should recognize the connected Xbox controller and proceed beyond the loading screen.

Actual Behavior:
The controller is not recognized, and the game remains stuck on the loading screen.

### Screenshot/video

![test](https://github.com/user-attachments/assets/ce2888db-fb4f-4de8-b766-20e72d9985f1)

**Comment by redphx** [comment]
#7
